### ISSUE TITLE
Tested With LLama3.1 Failed to convert text into a pydantic model 

### ISSUE THREAD

**Issue by hqnicolas** [mberman84/edu-crew#5]
Failed to convert text into a pydantic model due to the following error: Instructor does not support multiple tool calls, use List[Model] instead Using raw output instead.
[Flow._execute_single_listener] Error in method generate_educational_content: 'NoneType' object has no attribute 'sections'
Traceback (most recent call last):
  File "/app/edu-crew/.venv/lib/python3.11/site-packages/crewai/flow/flow.py", line 287, in _execute_single_listener
    listener_result = await self._execute_method(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edu-crew/.venv/lib/python3.11/site-packages/crewai/flow/flow.py", line 232, in _execute_method
    else method(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edu-crew/src/edu_flow/main.py", line 27, in generate_educational_content
    for section in plan.sections:
                   ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sections'

**Comment by hqnicolas** [comment]
if you have pydantic formating error, and just want to stop using pydantic:
 https://github.com/mberman84/edu-crew/pull/6/files#diff-f41e68ba6c8f1636a9c1a15cc9a4ce097b27747aca77474d627118771545926e
